# Generated by Django 4.1 on 2022-08-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password2',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
    ]
