# Generated by Django 4.1 on 2022-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_account_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
