# Generated by Django 4.1 on 2022-08-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_alter_account_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password2',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=30, verbose_name='password'),
        ),
    ]
